name: Sync EPG (TR)

on:
  schedule:
    - cron: "0 * * * *"   # Her saat (UTC) - istersen */30 yapabilirsin
  workflow_dispatch: {}    # Elle tetikleme

permissions:
  contents: write

concurrency:
  group: sync-epg
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout data branch
        uses: actions/checkout@v4
        with:
          ref: data
          fetch-depth: 0

      - name: Download & validate XML (in-repo temp file)
        env:
          EPG_URL: https://epg.tvcdn.net/guide/tr-guide.xml
          TARGET: epg.xml
        run: |
          set -euo pipefail

          TMP="${TARGET}.new"

          # İndir (retry + sıkıştırma desteği)
          curl -L --fail --retry 5 --retry-delay 10 --compressed \
               -H "User-Agent: FreeIPTV_TR/Sync (+github-actions)" \
               "$EPG_URL" -o "$TMP"

          # Boyut ve XML doğrulaması
          test -s "$TMP"  # boş dosya olmasın
          python - <<'PY'
import sys, xml.etree.ElementTree as ET
f = "epg.xml.new"
ET.parse(f)
print("XML OK")
PY

          # Değişmediyse çık
          if [ -f "$TARGET" ] && cmp -s "$TMP" "$TARGET"; then
            echo "No change in $TARGET"
            rm -f "$TMP"
            exit 0
          fi

          # Atomik güncelleme
          mv -f "$TMP" "$TARGET"

          # (Opsiyonel) .gz üret
          gzip -c "$TARGET" > "${TARGET}.gz"

      - name: Commit & push if changed (to data)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A
          if git diff --cached --quiet; then
            echo "Nothing to commit"
            exit 0
          fi

          MSG="update: epg.xml $(TZ='Europe/Istanbul' date '+%Y-%m-%d %H:%M %z')"
          git commit -m "$MSG"
          git push origin HEAD:data
